import {Muxer,ArrayBufferTarget} from 'https://esm.sh/mp4-muxer@5.2.2';

const IDS=['projectInput','projectButton','projectStatus','folderInput','folderButton','folderStatus','logoInput','logoButton','logoStatus','sceneCount','requiredCount','matchedCount','missingCount','codecStatus','canvas','duration','fps','bitrate','previewButton','renderButton','cancelButton','downloadButton','bar','status','log'];
const el=Object.fromEntries(IDS.map(id=>[id,document.getElementById(id)]));el.ctx=el.canvas.getContext('2d',{alpha:false});
const state={project:null,files:new Map(),images:new Map(),logo:null,mp4:null,codec:null,cancel:false,busy:false};
const W=1080,H=1350;
el.projectButton.onclick=()=>el.projectInput.click();el.folderButton.onclick=()=>el.folderInput.click();el.logoButton.onclick=()=>el.logoInput.click();el.projectInput.onchange=loadProject;el.folderInput.onchange=loadFolder;el.logoInput.onchange=loadLogo;el.previewButton.onclick=()=>drawProjectScene(0,.7);el.renderButton.onclick=renderMp4;el.cancelButton.onclick=()=>{state.cancel=true;setStatus('Cancelling after the current frame...')};el.downloadButton.onclick=()=>download(state.mp4,'cxo-montage-linkedin.mp4');
drawEmpty('Load project and images');checkCodec();

async function checkCodec(){if(!('VideoEncoder'in window)){el.codecStatus.textContent='Unavailable';return}const candidates=['avc1.420034','avc1.4d0034','avc1.640034'];for(const codec of candidates){try{const result=await VideoEncoder.isConfigSupported({codec,width:W,height:H,bitrate:10000000,framerate:30,hardwareAcceleration:'prefer-hardware',avc:{format:'avc'}});if(result.supported){state.codec=codec;el.codecStatus.textContent='Ready';log(`H.264 encoder supported: ${codec}`);validate();return}}catch(error){log(`${codec}: ${error.message}`)}}el.codecStatus.textContent='Unsupported';setStatus('H.264 WebCodecs is unavailable. Use current Microsoft Edge or Google Chrome.',true)}
async function loadProject(e){try{state.project=JSON.parse(await e.target.files[0].text());if(!state.project?.scenes||!state.project?.photoNames)throw new Error('Unsupported JSON structure');el.projectStatus.textContent=`${state.project.scenes.length} scenes`;el.sceneCount.textContent=state.project.scenes.length;log('Project loaded.');validate()}catch(err){setStatus(err.message,true)}}
async function loadFolder(e){state.files.clear();for(const file of e.target.files)if(file.type.startsWith('image/'))state.files.set(file.name,file);el.folderStatus.textContent=`${state.files.size} files`;log(`Folder loaded: ${state.files.size} files.`);await validate()}
async function loadLogo(e){const file=e.target.files[0];if(!file)return;state.logo=await decode(file);el.logoStatus.textContent=file.name;drawProjectScene(0,.7)}
async function validate(){if(!state.project||!state.files.size)return;const names=[...new Set(state.project.scenes.flatMap(s=>s.frames.map(f=>state.project.photoNames[f.photoId])).filter(Boolean))],missing=names.filter(n=>!state.files.has(n));el.requiredCount.textContent=names.length;el.matchedCount.textContent=names.length-missing.length;el.missingCount.textContent=missing.length;if(missing.length){setStatus(`Missing ${missing.length} images: ${missing.slice(0,3).join(', ')}`,true);disableRender();return}setStatus('Validation passed. Decoding required images...');state.images.clear();for(let i=0;i<names.length;i++){state.images.set(names[i],await decode(state.files.get(names[i])));setProgress((i+1)/names.length*.05);if(i%8===0)await yieldToBrowser()}setProgress(0);setStatus('Ready. Preview the first scene, then render MP4.');el.previewButton.disabled=false;el.renderButton.disabled=!state.codec;drawProjectScene(0,.7);log(`Validated and decoded ${names.length} images.`)}
function decode(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>resolve({img,url});img.onerror=()=>reject(new Error(`Could not decode ${file.name}`));img.src=url})}

async function renderMp4(){if(state.busy||!state.project||!state.codec)return;state.busy=true;state.cancel=false;state.mp4=null;el.renderButton.disabled=true;el.previewButton.disabled=true;el.cancelButton.disabled=false;el.downloadButton.disabled=true;const fps=Number(el.fps.value),duration=el.duration.value==='project'?Number(state.project.settings?.duration||120):Number(el.duration.value),total=Math.round(duration*fps),per=duration/state.project.scenes.length,target=new ArrayBufferTarget(),muxer=new Muxer({target,video:{codec:'avc',width:W,height:H},fastStart:'in-memory',firstTimestampBehavior:'offset'});let encoderError=null;const encoder=new VideoEncoder({output:(chunk,meta)=>muxer.addVideoChunk(chunk,meta),error:error=>{encoderError=error;log(`ENCODER ERROR: ${error.message}`)}});encoder.configure({codec:state.codec,width:W,height:H,bitrate:Number(el.bitrate.value),framerate:fps,hardwareAcceleration:'prefer-hardware',latencyMode:'quality',avc:{format:'avc'}});log(`Direct MP4 render: ${total} frames, ${fps} FPS, codec ${state.codec}.`);const started=performance.now();try{for(let n=0;n<total;n++){if(state.cancel)throw new DOMException('Render cancelled','AbortError');const sec=n/fps,si=Math.min(state.project.scenes.length-1,Math.floor(sec/per)),progress=(sec-si*per)/per;drawScene(state.project.scenes[si],progress);const timestamp=Math.round(n*1_000_000/fps),frame=new VideoFrame(el.canvas,{timestamp,duration:Math.round(1_000_000/fps)});encoder.encode(frame,{keyFrame:n%(fps*2)===0});frame.close();if(encoder.encodeQueueSize>6)await encoder.flush();if(encoderError)throw encoderError;if(n%12===0){setProgress(n/total);setStatus(`Encoding MP4 ${Math.round(n/total*100)}% · frame ${n}/${total}`);await yieldToBrowser()}}setStatus('Finalising MP4...');await encoder.flush();encoder.close();muxer.finalize();state.mp4=new Blob([target.buffer],{type:'video/mp4'});if(state.mp4.size<100000)throw new Error('The encoded MP4 is unexpectedly small.');setProgress(1);setStatus(`MP4 ready: ${formatBytes(state.mp4.size)}. Downloading now.`);log(`Completed in ${((performance.now()-started)/1000).toFixed(1)}s. File: ${formatBytes(state.mp4.size)}.`);el.downloadButton.disabled=false;download(state.mp4,'cxo-montage-linkedin.mp4')}catch(error){try{encoder.close()}catch{}setStatus(error.name==='AbortError'?'Render cancelled.':`Render failed: ${error.message}`,true);log(error.stack||error.message)}finally{state.busy=false;el.renderButton.disabled=false;el.previewButton.disabled=false;el.cancelButton.disabled=true;drawProjectScene(0,.7)}}

function drawProjectScene(index,progress){if(!state.project||!state.images.size)return;drawScene(state.project.scenes[index],progress)}
function drawScene(scene,progress){drawBackground(progress);[...scene.frames].sort((a,b)=>a.z-b.z).forEach(frame=>{const asset=state.images.get(state.project.photoNames[frame.photoId]);if(asset)drawFrame(asset.img,frame,progress)});drawLogo()}
function drawBackground(progress){const c=el.ctx,g=c.createLinearGradient(0,0,W,H);g.addColorStop(0,'#132949');g.addColorStop(1,'#071327');c.fillStyle=g;c.fillRect(0,0,W,H);c.save();c.globalAlpha=.2;c.strokeStyle='#31859d';for(let i=0;i<10;i++){const x=(i*150+progress*100)%1200-100,y=i*130;c.beginPath();c.moveTo(x,y);c.lineTo(x+300,y+65);c.stroke()}c.restore()}
function drawFrame(img,f,p){const c=el.ctx,m=motion(p,f.z),iw=img.naturalWidth,ih=img.naturalHeight;c.save();c.translate(m.x,m.y);c.beginPath();c.roundRect(f.x,f.y,f.w,f.h,Math.min(18,f.w/2,f.h/2));c.clip();const base=f.fit==='fit'?Math.min(f.w/iw,f.h/ih):Math.max(f.w/iw,f.h/ih),scale=base*(f.zoom||1)*(1+p*.025),dw=iw*scale,dh=ih*scale;c.drawImage(img,f.x+(f.w-dw)*(f.fx??.5),f.y+(f.h-dh)*(f.fy??.5),dw,dh);c.restore()}
function motion(p,i){const r=1-Math.max(0,Math.min(1,p)),s=state.project.settings?.motion||'dynamic';if(s==='elegant')return{x:0,y:r*28};if(s==='dynamic')return{x:r*(i%2?-48:48),y:0};return{x:0,y:r*48}}
function drawLogo(){if(!state.logo)return;const w=Number(state.project.settings?.logoSize||180),h=w*state.logo.img.naturalHeight/state.logo.img.naturalWidth,top=Number(state.project.settings?.logoTop||14);el.ctx.drawImage(state.logo.img,(W-w)/2,top,w,h)}
function drawEmpty(text){drawBackground(0);el.ctx.fillStyle='#ffffffbb';el.ctx.font='34px Barlow';el.ctx.textAlign='center';el.ctx.fillText(text,W/2,H/2);el.ctx.textAlign='start'}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),300000)}
function disableRender(){el.previewButton.disabled=true;el.renderButton.disabled=true}function setProgress(v){el.bar.style.width=`${Math.round(Math.max(0,Math.min(1,v))*100)}%`}function setStatus(s,error=false){el.status.textContent=s;el.status.style.color=error?'#ff8585':''}function log(s){el.log.textContent+=`${new Date().toLocaleTimeString()}  ${s}\n`;el.log.scrollTop=el.log.scrollHeight}function yieldToBrowser(){return new Promise(r=>setTimeout(r,0))}function formatBytes(n){return n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`}
